### ISSUE TITLE
Spelling Mistake in Error String for activating or deactivating a module

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [OXIDprojects/oxrun#48]
In the files ActiveCommand.php Line 78 and DeactivateCommand.php Line 79 are spelling Mistakes.  I have fixed them but dont't know how to contrbute to this project. How can i contribute my fix to the project?

**Comment by keywan-ghadami-oxid** [comment]
https://github.com/OXIDprojects/oxrun/pull/49

**Comment by Sebastian-Hirsch** [comment]
These two branches fix the mentioned issues. I will close the bugreport when they are merged into master

**Comment by keywan-ghadami-oxid** [comment]
I do not know what needs to be done next, but I guess @TumTum will create a new release that will include this fix together with some other things.

**Comment by TumTum** [comment]
Thank you the new Release has not any more the command.
