### ISSUE TITLE
PHP Fatal error on composer installl

### ISSUE THREAD

**Issue by mkrepp** [OXIDprojects/oxrun#54]
Updating component oxid-esales/developer-tools
PHP Fatal error:  Uncaught Error: Call to undefined method Oxrun\Command\Config\UpdateYaml::getDefaultName() in /var/www/oxid/vendor/symfony/console/DependencyInjection/AddConsoleCommandPass.php:61
Stack trace:
#0 /var/www/oxid/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\Console\DependencyInjection\AddConsoleCommandPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#1 /var/www/oxid/vendor/symfony/dependency-injection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Internal/Container/ContainerFactory.php(86): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /var/www/oxid/vendor/oxid-esales/oxideshop-ce/source/Internal/Container/ContainerFactory.php(65): OxidEsales\EshopCommunity\Internal\Container\ContainerFactory->getCompiledSymfonyContainer()

**Comment by mkrepp** [comment]
using the latest version, "oxidprojects/oxrun": "^5.0@RC"

**Comment by TumTum** [comment]
Which OXID version has you?

**Comment by mkrepp** [comment]
Community Edition 6.2.0

**Comment by TumTum** [comment]
i will ist test which that Version i have v6.2.3

**Comment by TumTum** [comment]
I was able to install it with CE 6.2.0:

```json
{
  "name": "oxid-esales/oxideshop-project",
  "type": "project",
  "minimum-stability": "RC",
  "require": {
    "oxid-esales/oxideshop-metapackage-ce": "v6.2.0",
    "oxidprojects/oxrun": "^5.0@RC"
  }
}
```

```shell
$: composer show | grep oxid

oxid-esales/oxideshop-ce                          v6.5.3     This package contains OXID eShop CE source code.
oxid-esales/oxideshop-composer-plugin             v4.1.0     This file is mean to be used to install OXID eShop compilation.
...
oxidprojects/oxrun                                5.0.0-RC5  Oxrun provides a cli toolset for the OXID eShop v6.x
...
```

is your `var/generated/generated_services.yaml` correct?

```yaml
imports:
  -
    resource: /var/www/oxideshop/vendor/oxid-esales/developer-tools/services.yaml
  -
    resource: /var/www/oxideshop/vendor/oxidprojects/oxrun/services.yaml
```

i have testet with PHP 7.2

**Comment by TumTum** [comment]
I think the problem has been solved
