### ISSUE TITLE
oxrun Commands not available after installation

### ISSUE THREAD

**Issue by makkus183** [OXIDprojects/oxrun#57]
I installed the package [as described](https://github.com/OXIDprojects/oxrun/tree/07e7e896f5b7ccbcf54d5d206bb910242957628c#installation) in the following environment:

- `PHP 7.4`
- `"oxid-esales/oxideshop-metapackage-pe": "v6.3.1"`

After Installation i have the following version in my composer.json:

```
    "require": {
        "oxid-esales/oxideshop-metapackage-pe": "v6.3.1",
       ...
        "oxidprojects/oxrun": "^5.0"
    },
```

But i cannot use the [commands oxrun is providing](https://github.com/OXIDprojects/oxrun#available-commands), the options are not available. I get the same result as before installing the tool:

`vendor/bin/oxrun` or `'vendor/bin/oe-console' ` is only giving me the following commands

```
Console Tool

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help                               Displays help for a command
  list                               Lists commands
 oe
  oe:module:activate                 Activates a module.
  oe:module:apply-configuration      Applies configuration for installed modules.
  oe:module:deactivate               Deactivates a module.
  oe:module:install-configuration    Install module configuration into project configuration file.Module configuration already present in the project configuration file will be overwritten.
  oe:module:reset-configurations     Resets changes in project configuration.
  oe:module:uninstall-configuration  Uninstall module configuration from project configuration file.
```

Testing one of the commands like:

`./vendor/bin/oxrun cache:clear` is giving me:

```

                                                           
  There are no commands defined in the "cache" namespace.  
                                                           

Failed to execute command ./vendor/bin/oxrun cache:clear: exit status 1

```

I can see the following entry in `var/generated/generated_services.yaml`:

`    resource: ../../vendor/oxidprojects/oxrun/services.yaml`

Am i missing something?

**Comment by TumTum** [comment]
First time you must manual clear the cache `rm -rf source/tmp/*` then will read all `oxrun` commands

**Comment by makkus183** [comment]
@TumTum thanks a lot for answering this so quickly and solving problems of an oxid noob. Clearing the cache made all the commands available.
 
Is this maybe worth a note in the [Installation instructions](https://github.com/OXIDprojects/oxrun#installation) if someone like me wants to use this great project and is new to oxid?

**Comment by TumTum** [comment]
I am pleased that you made a pull request to support this project.
